[package]
name = "traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
rustflags = ["-A", "unused_variables"]

[profile.release]
rustflags = ["-A", "unused_variables"]
